# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aef5349a288881bedd1859d90cf213709b9c33f6fa0c9e9d558c167141d8dcae523a2ac30996b47c971c8efed3dff7ab981a8b06e9df077e24aea4e351f063ce

test:
  secret_key_base: 9542161622bf420f60bdebc2fc9943ce6539f6a0672c9b1f21cd4fb762a587259223479e83e04b4e2b4a99e6256852cca104f2fffbbfd84723a231831a06ef32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
